# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
parameters:
#liip_imagine.optipng.binary: /usr/bin/optipng
liip_imagine:
  webp:
    generate: true
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "imagick"
  # configure resolvers
  resolvers:
    # setup the default resolver
    default:
      # use the default web path
      web_path: ~
  # your filter sets are defined here
  filter_sets:
    cache: ~
    lazy:
      jpeg_quality: 20
      png_compression_level: 1
      filters:
        relative_resize:
          widen: 60

    grand:
      jpeg_quality: 80
      png_compression_level: 6
      filters:
        auto_rotate: ~
        relative_resize:
          widen: 900

    moyen:
      jpeg_quality: 80
      png_compression_level: 6
      filters:
        auto_rotate: ~
        relative_resize:
          widen: 600

    petit:
      jpeg_quality: 80
      png_compression_level: 6
      filters:
        auto_rotate: ~
        relative_resize:
          widen: 300

    mini:
      jpeg_quality: 80
      png_compression_level: 6
      filters:
        auto_rotate: ~
        relative_resize:
          widen: 100

    icone:
      jpeg_quality: 80
      png_compression_level: 6
      filters:
        auto_rotate: ~
        relative_resize:
          widen: 32

    label:
      jpeg_quality: 80
      png_compression_level: 6
      filters:
        auto_rotate: ~
        relative_resize:
          widen: 100

    urne:
      jpeg_quality: 80
      png_compression_level: 6
      filters:
        auto_rotate: ~
        relative_resize:
          widen: 100
    #pngspeed : #install optipng by apt
    #    quality : 75
    #    post_processors:
    #        optipng: { strip_all: false, level: 5 }     #on garde les exif
